export const harmonicFields: Record<
  string,
  { chord: string; degree: string }[]
> = {
  C: [
    { chord: "C", degree: "I" },
    { chord: "Dm", degree: "ii" },
    { chord: "Em", degree: "iii" },
    { chord: "F", degree: "IV" },
    { chord: "G", degree: "V" },
    { chord: "Am", degree: "vi" },
    { chord: "Bdim", degree: "vii°" },
  ],
  D: [
    { chord: "D", degree: "I" },
    { chord: "Em", degree: "ii" },
    { chord: "F#m", degree: "iii" },
    { chord: "G", degree: "IV" },
    { chord: "A", degree: "V" },
    { chord: "Bm", degree: "vi" },
    { chord: "C#dim", degree: "vii°" },
  ],
  E: [
    { chord: "E", degree: "I" },
    { chord: "F#m", degree: "ii" },
    { chord: "G#m", degree: "iii" },
    { chord: "A", degree: "IV" },
    { chord: "B", degree: "V" },
    { chord: "C#m", degree: "vi" },
    { chord: "D#dim", degree: "vii°" },
  ],
  F: [
    { chord: "F", degree: "I" },
    { chord: "Gm", degree: "ii" },
    { chord: "Am", degree: "iii" },
    { chord: "Bb", degree: "IV" },
    { chord: "C", degree: "V" },
    { chord: "Dm", degree: "vi" },
    { chord: "Edim", degree: "vii°" },
  ],
  G: [
    { chord: "G", degree: "I" },
    { chord: "Am", degree: "ii" },
    { chord: "Bm", degree: "iii" },
    { chord: "C", degree: "IV" },
    { chord: "D", degree: "V" },
    { chord: "Em", degree: "vi" },
    { chord: "F#dim", degree: "vii°" },
  ],
  A: [
    { chord: "A", degree: "I" },
    { chord: "Bm", degree: "ii" },
    { chord: "C#m", degree: "iii" },
    { chord: "D", degree: "IV" },
    { chord: "E", degree: "V" },
    { chord: "F#m", degree: "vi" },
    { chord: "G#dim", degree: "vii°" },
  ],
  B: [
    { chord: "B", degree: "I" },
    { chord: "C#m", degree: "ii" },
    { chord: "D#m", degree: "iii" },
    { chord: "E", degree: "IV" },
    { chord: "F#", degree: "V" },
    { chord: "G#m", degree: "vi" },
    { chord: "A#dim", degree: "vii°" },
  ],
};
